services:
  ambev.developerevaluation.webapi:
    container_name: ambev_developer_evaluation_webapi
    image: ${DOCKER_REGISTRY-}ambevdeveloperevaluationwebapi
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Host=ambev_developer_evaluation_database;Port=5432;Database=developer_evaluation;Username=developer;Password=ev@luAt10n
      - ConnectionStrings__TestIntegrationConnection=Host=ambev_developer_evaluation_database;Port=5432;Database=developer_evaluation_it;Username=developer;Password=ev@luAt10n
    ports:
      - "8080:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - ambev.developerevaluation.database
      - ambev.developerevaluation.nosql
      - ambev.developerevaluation.cache
    
  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: "ev@luAt10n"
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  ambev.developerevaluation.nosql:
    container_name: ambev_developer_evaluation_nosql
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: "ev@luAt10n"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  ambev.developerevaluation.cache:
    container_name: ambev_developer_evaluation_cache
    image: redis:7.4.1-alpine
    command: ["redis-server", "--requirepass", "ev@luAt10n"]
    ports:
      - "6379:6379"
    restart: unless-stopped

  ambev.developerevaluation.ui:
    build:
      context: src/Ambev.DeveloperEvaluation.UI
      dockerfile: Dockerfile
    depends_on:
      - ambev.developerevaluation.webapi
    environment:
      - API_BASE_URL=http://ambev.developerevaluation.webapi:8080
    ports:
      - "80:80"

volumes:
  pgdata:
  mongodata:
  pgdata_it:  